[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"


[project]
name = "repoman"
version = "0.1.0"
description = "A Python project template generator using copier and Jinja2"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "catppuccin>=2.5.0",
    "copier>=9.11.0",
    "copier-template-extensions>=0.3.3",
    "fastapi>=0.128.0",
    "mlflow>=3.9.0",
    "pydantic>=2.12.0",
    "pydantic-settings>=2.12.0",
    "pydriller>=2.0",
    "rich>=14.3.0",
    "typer>=0.17.3",
]

[project.scripts]
repoman = "repoman:cli"

[tool.uv]
default-groups = ["maintain", "ci", "docs"]



[dependency-groups]

dev = [
    "ipykernel>=6.29.5",
    "glob2==0.6",
    "ipywidgets>=8.1.5",
]

maintain = [
    "bump2version>=1.0.1",
    "nb-clean>=4.0.1",
    "monkeytype>=23.3.0",
]
ci = [
    "coverage>=7.13.0",
    "interrogate>=1.7.0",
    "mypy>=1.19.0",
    "pytest>=9.0.0",
    "pytest-cov>=7.0.0",
    "pytest-randomly>=4.0.0",
    "pytest-xdist>=3.8.0",
    "ruff>=0.14.0",
    "types-markdown>=3.6",
    "types-pyyaml>=6.0",
]
docs = [
    "markdown-callouts>=0.4.0",
    "markdown-exec>=1.12.0",
    "mkdocs-coverage>=2.0.0",
    "mkdocs-gen-files>=0.6.0",
    "mkdocs-git-revision-date-localized-plugin>=1.5.0",
    "mkdocs-literate-nav>=0.6.1",
    "mkdocs-material>=9.7.0",
    "mkdocs-minify-plugin>=0.8.0",
    "mkdocs-jupyter>=0.24.8",
    "mkdocs>=1.6.1",
    "mkdocstrings[python]>=1.0.0",
    "mkdocs-table-reader-plugin>=3.1.0",
    "mkdocs-charts-plugin>=0.0.13",
    "pymdown-extensions>=10.12",
]


