stages:
  - stage: UnitTests
    displayName: "Run CI Tests"
    condition: always()
    
    variables:
      python.version: '3.12'
      UV_VENV_DIR: .venv
    
    jobs:
      - job: Install_dependencies_and_cache
        displayName: "Installing dependencies"
        workspace:
          clean: all
        pool:
          vmImage: 'ubuntu-22.04'
      
        steps:
          - checkout: self
          - script: curl -LsSf https://astral.sh/uv/install.sh | sh
            displayName: "Install uv"

          - script: |
              uv cache dir > uv_cache_dir.txt
              echo "##vso[task.setvariable variable=uv_cache_dir]$(cat uv_cache_dir.txt)"
            displayName: "Set cache directory"

          - task: Cache@2
            displayName: "Upload uv cache"
            inputs:
              key: '"uv"|$(Agent.OS)|pyproject.toml|uv.lock'
              restoreKeys: |
                "uv"|$(Agent.OS)|pyproject.toml|uv.lock
                "uv"|$(Agent.OS)|pyproject.toml
                "uv"|$(Agent.OS)
              path: $(UV_CACHE_DIR)

          - script: |
              make install
            displayName: "Install dependencies"

          - script: |
              uv cache prune --ci
            displayName: 'Prune uv cache'


      - job: Run_format_tests
        pool: 
          vmImage: 'ubuntu-22.04'
        dependsOn: Install_dependencies_and_cache
        displayName: "Checking Formating "
        steps:
          - checkout: self
  
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'

          - script: curl -LsSf https://astral.sh/uv/install.sh | sh
            displayName: "Install uv"

          - task: Cache@2
            displayName: "Restore uv cache"
            inputs:
              key: '"uv"|$(Agent.OS)|pyproject.toml|uv.lock'
              restoreKeys: |
                "uv"|$(Agent.OS)|pyproject.toml|uv.lock
                "uv"|$(Agent.OS)|pyproject.toml
                "uv"|$(Agent.OS)
              path: $(UV_CACHE_DIR)

          - script: |
              make check-format
            displayName: 'Check formatting'

          - script: |
              uv cache prune --ci
            displayName: 'Prune uv cache'


      - job: Run_Unit_tests
        pool: 
          vmImage: 'ubuntu-22.04'
        dependsOn: Run_format_tests
        displayName: "Running unit tests"
        steps:
          - checkout: self
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'

          - script: curl -LsSf https://astral.sh/uv/install.sh | sh
            displayName: "Install uv"
          
          - script: |
              uv cache dir > uv_cache_dir.txt
              echo "##vso[task.setvariable variable=uv_cache_dir]$(cat uv_cache_dir.txt)"
            displayName: "Save uv cache"

          - task: Cache@2
            displayName: "Restore uv cache"
            inputs:
              key: '"uv"|$(Agent.OS)|pyproject.toml'
              restoreKeys: |
                "uv"|$(Agent.OS)|pyproject.toml
                "uv"|$(Agent.OS)
              path: $(UV_CACHE_DIR)

          - script: |
              make install
            displayName: "Sync dependencies"

          - script: |
              make test
            displayName: 'Run unit tests'

          - task: PublishCodeCoverageResults@2
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: 'coverage-unit.xml'
              failIfCoverageEmpty: true
            displayName: 'Publish unit test coverage'

          - script: |
              uv cache prune --ci
            displayName: 'Prune uv cache'


      - job: Check_documentation
        pool: 
          vmImage: 'ubuntu-22.04'
        dependsOn: Run_format_tests
        displayName: "Checking Documentation"
        continueOnError: true
        steps:
          - checkout: self
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'

          - script: curl -LsSf https://astral.sh/uv/install.sh | sh
            displayName: "Install uv"


          - script: |
              make check-docs
            displayName: 'Check documentation'

      - job: Build_deployment_base_image
        pool: 
          vmImage: 'ubuntu-22.04'
        dependsOn: Run_Unit_tests 
        continueOnError: true
        displayName: "Building Deployment Base Image"
        variables:
          DOCKER_BUILDKIT: '1'        # faster, leaner builds
          BUILDKIT_PROGRESS: 'plain'
        steps:
          - checkout: self
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'

          - task: Docker@2
            displayName: 'Docker Login'
            inputs:
              containerRegistry: '{{ container_registry }}'
              command: 'login'

          - script: |
              make build-deploy-base
            displayName: "Build Deployment Base Image"

          - script: |
              make push-deploy-base
            displayName: "Push Deployment Base Image"

