parameters:
  - name: deployment
    type: string
    displayName: 'Deployment folder '

stages:
  - stage: SmokeTests_${{ replace(replace(parameters.deployment, '/', '_'), '-', '_') }}
    displayName: "Smoke Tests: ${{ parameters.deployment }}"
    
    variables:
      group : '{{ python_package_import_name }}-CI'
      python.version: '3.12'
      DEPENDENCIES_VERSION: "latest"  # |"pre-release" | "minimum-version"
      UV_CACHE_DIR: $(Agent.TempDirectory)/cache/uv
      connection_string: ''

    jobs:
      - job: smoke_test  
        displayName: "Run Smoke Tests for ${{ parameters.deployment }}"
        workspace:
          clean: all
        pool:
          vmImage: 'ubuntu-22.04'       

        steps:
        - checkout: self
          submodules: true

        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(python.version)'
          displayName: 'Use Python $(python.version)'

        - script: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
          displayName: 'Install uv'

        - script: |
            uv sync --only-group smoke --no-default-groups
            uv cache dir > uv_cache_dir.txt
            echo "##vso[task.setvariable variable=uv_cache_dir]$(cat uv_cache_dir.txt)"
          displayName: 'Install smoke dependencies'

      
        - script: |
            if [ -z "$(AZURE_STORAGE_CONNECTION_STRING)" ]; then
              echo "ERROR: AZURE_STORAGE_CONNECTION_STRING is empty."
              exit 1
            else
              echo "AZURE_STORAGE_CONNECTION_STRING is provided: $(AZURE_STORAGE_CONNECTION_STRING)."
              echo "##vso[task.setvariable variable=connection_string]$(AZURE_STORAGE_CONNECTION_STRING)"      
            fi
          displayName: 'Get azure storage connection image'

        - task: Docker@2
          displayName: Docker_Login
          inputs:
            containerRegistry: '{{ container_registry }}'
            command: 'login'

        - script: | 
            make pull-deploy-base
          displayName: 'build deployment baseimage' 

        - script : |
            # Create a container from the existing image
            make build-deploy-temp-image-with-config target.deployment=${{parameters.deployment}}
          displayName: 'build deployment image'  
        
        - script: |
            echo '$(System.DefaultWorkingDirectory)'
            make smoke-test target.deployment=${{parameters.deployment}}
          displayName: 'Run smoke tests'
          env:
            AZURE_STORAGE_CONNECTION_STRING: $(connection_string)

        