parameters:
  - name: deployment
    type: string
    displayName: 'Deployment folder (e.g., dtna/mth)'

stages:
  - stage: SmokeTests_${{ replace(replace(parameters.deployment, '/', '_'), '-', '_') }}
    displayName: "Smoke Tests: ${{ parameters.deployment }}"
    
    variables:
      group : 'loopr-ml-CI'
      python.version: '3.12'
      DEPENDENCIES_VERSION: "latest"  # |"pre-release" | "minimum-version"
      UV_CACHE_DIR: $(Agent.TempDirectory)/cache/uv
      connection_string: ''

    jobs:
      - job: smoke_test  
        displayName: "Run Smoke Tests for ${{ parameters.deployment }}"
        workspace:
          clean: all
        pool:
          vmImage: 'ubuntu-22.04'       

        steps:
        - checkout: self
          submodules: true

        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(python.version)'
          displayName: 'Use Python $(python.version)'

        - script: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
          displayName: 'Install uv'

        - script: |
            uv sync --only-group smoke --no-default-groups
            uv cache dir > uv_cache_dir.txt
            echo "##vso[task.setvariable variable=uv_cache_dir]$(cat uv_cache_dir.txt)"
          displayName: 'Install smoke dependencies'

      
        - script: |
            if [ -z "$(AZURE_STORAGE_CONNECTION_STRING)" ]; then
              echo "ERROR: AZURE_STORAGE_CONNECTION_STRING is empty."
              exit 1
            else
              echo "AZURE_STORAGE_CONNECTION_STRING is provided: $(AZURE_STORAGE_CONNECTION_STRING)."
              echo "##vso[task.setvariable variable=connection_string]$(AZURE_STORAGE_CONNECTION_STRING)"      
            fi
          displayName: 'Get azure storage connection image'

        - task: Docker@2
          displayName: Docker_Login
          inputs:
            containerRegistry: 'loopr_container_registry'
            command: 'login'

        - script: | 
            make pull-deploy-base
          displayName: 'build deployment baseimage' 

        - script : |
            # Create a container from the existing image
            make build-deploy-temp-image-with-config target.deployment=${{parameters.deployment}}
          displayName: 'build deployment image'  
        
        - script: |
            echo '$(System.DefaultWorkingDirectory)'
            make smoke-test target.deployment=${{parameters.deployment}}
          displayName: 'Run smoke tests'
          env:
            AZURE_STORAGE_CONNECTION_STRING: $(connection_string)

        # - script : |
        #     docker tag $(image_name):$(image_tag) looprcontainerregistry.azurecr.io/$(image_name):$(image_tag)
        #     docker push looprcontainerregistry.azurecr.io/$(image_name):$(image_tag)
        #   displayName: 'push deployment image'  

        # - script: |
        #     echo "Deleting local image: $(image_name):$(image_tag)"
        #     docker rmi $(image_name):$(image_tag) || true
        #     docker rmi looprcontainerregistry.azurecr.io/$(image_name):$(image_tag) || true
        #   displayName: 'Delete deployment image from pipeline'

        # - task: AzureCLI@2
        #   displayName: Deleting Old Images from ACR
        #   inputs:
        #     azureSubscription: 'loopr-prod'
        #     scriptType: 'bash'
        #     scriptLocation: 'inlineScript'
        #     inlineScript: |
        #       # Get the 5 latest tags (newline separated)
        #       latest_tags=$(az acr repository show-tags --name looprcontainerregistry.azurecr.io --repository $(image_name) --top 5 --orderby time_desc --output tsv)
        #       echo "Latest 5 tags:"
        #       echo "${latest_tags}"

        #       # Get all tags (newline separated)
        #       all_tags=$(az acr repository show-tags --name looprcontainerregistry.azurecr.io --repository $(image_name) --output tsv)
        #       echo "All tags:"
        #       echo "${all_tags}"

        #       # Convert latest_tags to a grep pattern
        #       pattern=$(echo "${latest_tags}" | awk '{print "^"$0"$"}' | paste -sd'|' -)

        #       # Find tags to delete (not in latest_tags)
        #       tags_to_delete=$(echo "${all_tags}" | grep -Ev "${pattern}")

        #       echo "Tags to delete:"
        #       echo "${tags_to_delete}"

        #       # Delete old tags
        #       if [ -n "${tags_to_delete}" ]; then
        #         while IFS= read -r tag; do
        #           if [ -n "$tag" ]; then
        #             echo "Deleting image: $(image_name):${tag}"
        #             az acr repository delete --name looprcontainerregistry.azurecr.io --image $(image_name):${tag} --yes
        #           fi
        #         done <<< "${tags_to_delete}"
        #       else
        #         echo "No old tags to delete."
        #       fi       