FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    clang-format \
    cmake \
    curl \
    doxygen \
    gdb \
    git \
    meson \
    nano \
    ninja-build \
    pkg-config \
    python3-pip \
    python3-venv \
    unzip \
    vim \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces/{{ project_name }}
