# azure-pipelines.yml
trigger:
  - main
  - "*.*.x"

variables:
    - group: "loopr-ml-CI"

parameters:
  - name: deployments
    type: object
    default:
    # - hnk/irv # No longer deployed.
    - dtna/mth
    - gaf/ens
    - saf/sealant


stages:
  - template: stages/ci.yml
  # One stage per deployment (each on its own VM)
  - ${{ each d in parameters.deployments }}:
    - template: stages/smokes.yml
      parameters:
        deployment: ${{ d }}

    

