# azure-pipelines.yml
trigger:
  - main
  - "*.*.x"

variables:
    - group: "{{ python_package_import_name }}-CI"

parameters:
  - name: deployments
    type: object
    default:
    {% for deployment in deployments %}
    - {{ deployment }}
    {% endfor %}

stages:
  - template: stages/ci.yml
  # One stage per deployment (each on its own VM)
  - ${{ each d in parameters.deployments }}:
    - template: stages/smokes.yml
      parameters:
        deployment: ${{ d }}

    

